// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCazSReVFXt0D0MYREJfn1PbwZuyNg9Axw',
    appId: '1:621248568025:web:4d91bd758ab1e6bf7dfcc8',
    messagingSenderId: '621248568025',
    projectId: 'assistente-financeiro-ai',
    authDomain: 'assistente-financeiro-ai.firebaseapp.com',
    storageBucket: 'assistente-financeiro-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCRr4cXWQditJtZnkiSfymK7SwECTBG-Y',
    appId: '1:621248568025:android:27548fa68d04a60d7dfcc8',
    messagingSenderId: '621248568025',
    projectId: 'assistente-financeiro-ai',
    storageBucket: 'assistente-financeiro-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZR3430wf9ILsIJ26Dp6KaJe9gWsf3gDY',
    appId: '1:621248568025:ios:4591310c6aefffcf7dfcc8',
    messagingSenderId: '621248568025',
    projectId: 'assistente-financeiro-ai',
    storageBucket: 'assistente-financeiro-ai.firebasestorage.app',
    iosBundleId: 'com.assistentefinanceiro.assistenteFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZR3430wf9ILsIJ26Dp6KaJe9gWsf3gDY',
    appId: '1:621248568025:ios:4591310c6aefffcf7dfcc8',
    messagingSenderId: '621248568025',
    projectId: 'assistente-financeiro-ai',
    storageBucket: 'assistente-financeiro-ai.firebasestorage.app',
    iosBundleId: 'com.assistentefinanceiro.assistenteFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCazSReVFXt0D0MYREJfn1PbwZuyNg9Axw',
    appId: '1:621248568025:web:b70cabfa6385af2d7dfcc8',
    messagingSenderId: '621248568025',
    projectId: 'assistente-financeiro-ai',
    authDomain: 'assistente-financeiro-ai.firebaseapp.com',
    storageBucket: 'assistente-financeiro-ai.firebasestorage.app',
  );

}